"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type Student = { id: string; usn: string; name: string; email: string; department: string; semester: number; role: "STUDENT" | "ADMIN" };
type Subject = { id: string; code: string; name: string; credits: number };
type Tab = "students" | "records" | "subjects";

export default function AdminConsole({ students, subjects }: { students: Student[]; subjects: Subject[] }) {
  const [tab, setTab] = useState<Tab>("students");
  const [message, setMessage] = useState("");
  const router = useRouter();
  async function request(path: string, method: string, data?: Record<string, unknown>) { const response = await fetch(path, { method, headers: { "Content-Type": "application/json" }, body: data ? JSON.stringify(data) : undefined }); const body = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(body?.error ?? "Request failed"); router.refresh(); }
  async function submit(event: FormEvent<HTMLFormElement>, path: string, method = "POST") { event.preventDefault(); setMessage(""); try { await request(path, method, Object.fromEntries(new FormData(event.currentTarget))); event.currentTarget.reset(); setMessage("Saved successfully."); } catch (error) { setMessage(error instanceof Error ? error.message : "Request failed."); } }
  return <div><div className="mb-6 flex flex-wrap gap-2">{(["students", "records", "subjects"] as Tab[]).map(item => <button key={item} onClick={() => setTab(item)} className={`rounded-xl px-4 py-2 text-sm font-semibold capitalize ${tab === item ? "bg-violet-600 text-white" : "bg-white text-slate-600 shadow-sm dark:bg-slate-900 dark:text-slate-300"}`}>{item}</button>)}</div>{message && <p className="mb-5 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300">{message}</p>}{tab === "students" && <Students students={students} submit={submit} request={request}/>} {tab === "records" && <Records students={students} subjects={subjects} submit={submit}/>} {tab === "subjects" && <Subjects subjects={subjects} submit={submit} request={request}/>}</div>;
}

function Students({ students, submit, request }: { students: Student[]; submit: (e: FormEvent<HTMLFormElement>, p: string, m?: string) => Promise<void>; request: (p: string, m: string, d?: Record<string, unknown>) => Promise<void> }) { const [selected, setSelected] = useState(students[0]?.id ?? ""); const student = students.find(x => x.id === selected); return <div className="grid gap-6 xl:grid-cols-2"><Form title="Add student" onSubmit={e => submit(e, "/api/admin/students")}><Input name="usn" label="USN" required/><Input name="name" label="Full name" required/><Input name="email" label="Email" type="email" required/><Input name="department" label="Department" defaultValue="Computer Science" required/><Input name="semester" label="Semester" type="number" defaultValue="4" required/><Input name="password" label="Initial password" type="password" required/><Save label="Add student"/></Form><Form title="Edit student" onSubmit={e => student && submit(e, `/api/admin/students/${student.id}`, "PATCH")}><label className="block text-sm font-medium">Student<select value={selected} onChange={e => setSelected(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 bg-transparent p-2.5 dark:border-slate-700">{students.map(x => <option key={x.id} value={x.id}>{x.usn} — {x.name}</option>)}</select></label>{student && <div key={student.id}><Input name="usn" label="USN" defaultValue={student.usn}/><Input name="name" label="Full name" defaultValue={student.name}/><Input name="email" label="Email" defaultValue={student.email}/><Input name="department" label="Department" defaultValue={student.department}/><Input name="semester" label="Semester" type="number" defaultValue={String(student.semester)}/><Input name="password" label="New password (optional)" type="password"/><Save label="Save changes"/></div>}</Form><div className="card xl:col-span-2 overflow-x-auto p-0"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500 dark:bg-slate-800"><tr><th className="p-4">USN</th><th className="p-4">Student</th><th className="p-4">Semester</th><th className="p-4"></th></tr></thead><tbody>{students.map(x => <tr key={x.id} className="border-t border-slate-100 dark:border-slate-800"><td className="p-4 font-medium">{x.usn}</td><td className="p-4">{x.name}</td><td className="p-4">{x.semester}</td><td className="p-4 text-right"><button onClick={() => request(`/api/admin/students/${x.id}`, "DELETE").catch(() => {})} className="text-rose-600">Delete</button></td></tr>)}</tbody></table></div></div> }

function Records({ students, subjects, submit }: { students: Student[]; subjects: Subject[]; submit: (e: FormEvent<HTMLFormElement>, p: string, m?: string) => Promise<void> }) { return <div className="grid gap-6 xl:grid-cols-3"><Form title="Add attendance" onSubmit={e => submit(e, "/api/admin/attendance")}><StudentSelect students={students}/><SubjectSelect subjects={subjects}/><Input name="percentage" label="Percentage" type="number" required/><Save label="Save attendance"/></Form><Form title="Add marks" onSubmit={e => submit(e, "/api/admin/marks")}><StudentSelect students={students}/><SubjectSelect subjects={subjects}/><Input name="internalMarks" label="Internal marks / 30" type="number" required/><Input name="finalMarks" label="Final marks / 70" type="number" required/><Save label="Save marks"/></Form><Form title="Add payment" onSubmit={e => submit(e, "/api/admin/payments")}><StudentSelect students={students}/><Input name="amount" label="Amount (₹)" type="number" required/><Input name="paymentDate" label="Payment date" type="date" required/><label className="block text-sm font-medium">Status<select name="status" className="mt-1 w-full rounded-lg border border-slate-200 bg-transparent p-2.5 dark:border-slate-700"><option value="PENDING">Pending</option><option value="PAID">Paid</option><option value="OVERDUE">Overdue</option></select></label><Save label="Add payment"/></Form></div> }

function Subjects({ subjects, submit, request }: { subjects: Subject[]; submit: (e: FormEvent<HTMLFormElement>, p: string, m?: string) => Promise<void>; request: (p: string, m: string, d?: Record<string, unknown>) => Promise<void> }) { return <div className="grid gap-6 xl:grid-cols-3"><Form title="Add subject" onSubmit={e => submit(e, "/api/admin/subjects")}><Input name="code" label="Subject code" required/><Input name="name" label="Subject name" required/><Input name="credits" label="Credits" type="number" required/><Save label="Add subject"/></Form><div className="card xl:col-span-2"><h2 className="section-title">Subjects</h2><div className="mt-4 space-y-3">{subjects.map(x => <div key={x.id} className="flex items-center justify-between border-b border-slate-100 pb-3 last:border-0 dark:border-slate-800"><div><p className="font-semibold">{x.name}</p><p className="text-sm text-slate-500">{x.code} · {x.credits} credits</p></div><div className="flex gap-3"><button onClick={() => { const name = window.prompt("Subject name", x.name); const credits = window.prompt("Credits", String(x.credits)); if (name && credits) request(`/api/admin/subjects/${x.id}`, "PATCH", { name, credits }).catch(() => {}); }} className="text-violet-600">Edit</button><button onClick={() => request(`/api/admin/subjects/${x.id}`, "DELETE").catch(() => {})} className="text-rose-600">Delete</button></div></div>)}</div></div></div> }

function Form({ title, onSubmit, children }: { title: string; onSubmit: (e: FormEvent<HTMLFormElement>) => void; children: React.ReactNode }) { return <form onSubmit={onSubmit} className="card space-y-3"><h2 className="section-title">{title}</h2>{children}</form> }
function Input({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="block text-sm font-medium">{label}<input {...props} className="mt-1 w-full rounded-lg border border-slate-200 bg-transparent p-2.5 outline-none focus:border-violet-500 dark:border-slate-700"/></label> }
function StudentSelect({ students }: { students: Student[] }) { return <label className="block text-sm font-medium">Student<select name="studentId" required className="mt-1 w-full rounded-lg border border-slate-200 bg-transparent p-2.5 dark:border-slate-700">{students.map(x => <option key={x.id} value={x.id}>{x.usn} — {x.name}</option>)}</select></label> }
function SubjectSelect({ subjects }: { subjects: Subject[] }) { return <label className="block text-sm font-medium">Subject<select name="subjectId" required className="mt-1 w-full rounded-lg border border-slate-200 bg-transparent p-2.5 dark:border-slate-700">{subjects.map(x => <option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label> }
function Save({ label }: { label: string }) { return <button className="mt-2 rounded-lg bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-violet-700">{label}</button> }
