"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { student } from "@/lib/mock-data";
import { Icon } from "./icons";
import ThemeToggle from "./theme-toggle";
import SignOutButton from "./sign-out-button";

const nav = [["/dashboard", "Dashboard", "dashboard"], ["/profile", "Profile", "user"], ["/attendance", "Attendance", "calendar"], ["/marks", "Marks", "chart"], ["/subjects", "Subjects", "book"], ["/payments", "Payments", "card"]] as const;
export default function PortalShell({ children, isAdmin = false }: { children: React.ReactNode; isAdmin?: boolean }) {
  const path = usePathname(); const [open, setOpen] = useState(false);
  const sidebar = <aside className="flex h-full w-64 flex-col bg-[#171a34] px-4 py-6 text-slate-300"><Link href="/dashboard" className="mb-10 flex items-center gap-3 px-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-violet-500 text-lg font-black text-white">C</span><span className="text-lg font-bold text-white">Campus Hub</span></Link><nav className="space-y-1">{nav.map(([href, label, icon]) => <Link key={href} onClick={() => setOpen(false)} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition ${path === href ? "bg-violet-500 text-white shadow-lg shadow-violet-900/30" : "hover:bg-white/10 hover:text-white"}`}><Icon name={icon} className="h-5 w-5"/>{label}</Link>)}{isAdmin && <Link href="/admin" className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium transition ${path === "/admin" ? "bg-violet-500 text-white shadow-lg shadow-violet-900/30" : "hover:bg-white/10 hover:text-white"}`}><Icon name="dashboard" className="h-5 w-5"/>Admin console</Link>}</nav><div className="mt-auto border-t border-white/10 pt-5"><SignOutButton/></div></aside>;
  return <div className="min-h-screen lg:flex"><div className="fixed inset-0 z-40 lg:hidden" aria-hidden={!open}>{open && <><button aria-label="Close menu" onClick={() => setOpen(false)} className="absolute inset-0 bg-slate-950/50"/><div className="relative h-full">{sidebar}</div></>}</div><div className="hidden lg:fixed lg:inset-y-0 lg:flex">{sidebar}</div><main className="min-h-screen flex-1 lg:ml-64"><header className="flex h-20 items-center justify-between border-b border-slate-200 bg-white px-4 dark:border-slate-800 dark:bg-slate-900 sm:px-7"><button onClick={() => setOpen(true)} className="rounded-lg p-2 lg:hidden"><Icon name="menu" className="h-6 w-6"/></button><div className="hidden sm:block"><p className="text-sm font-semibold text-slate-900 dark:text-white">Welcome back, {student.name.split(" ")[0]}!</p><p className="text-xs text-slate-500">Here is what is happening today.</p></div><div className="ml-auto flex items-center gap-2"><ThemeToggle/><button aria-label="Notifications" className="rounded-xl p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><Icon name="bell" className="h-5 w-5"/></button><Link href="/profile" className="ml-1 grid h-9 w-9 place-items-center rounded-full bg-violet-100 text-sm font-bold text-violet-700 dark:bg-violet-950 dark:text-violet-300">AS</Link></div></header><div className="mx-auto max-w-7xl p-4 sm:p-7">{children}</div></main></div>;
}
