import PageHeader from "@/components/page-header";
import { getCurrentStudent } from "@/lib/current-student";
import { prisma } from "@/lib/prisma";

const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const displayStatus = (status: string) => status.charAt(0) + status.slice(1).toLowerCase();

export default async function PaymentsPage() {
  const student = await getCurrentStudent();
  const payments = await prisma.payment.findMany({ where: { studentId: student.id }, orderBy: { paymentDate: "desc" } });
  const balance = payments.filter((payment) => payment.status === "PENDING" || payment.status === "OVERDUE").reduce((sum, payment) => sum + payment.amount.toNumber(), 0);
  return <><PageHeader title="Payments" description="View fees, dues and payment history."/>{balance > 0 && <section className="mb-6 flex flex-col justify-between gap-4 rounded-2xl bg-gradient-to-r from-violet-600 to-indigo-700 p-6 text-white sm:flex-row sm:items-center"><div><p className="text-sm font-medium text-violet-200">Outstanding balance</p><p className="mt-1 text-3xl font-bold">{currency.format(balance)}</p><p className="mt-1 text-sm text-violet-100">Please settle the outstanding fee at your earliest convenience.</p></div><button className="rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-violet-700 transition hover:bg-violet-50">Pay now</button></section>}<div className="card overflow-x-auto p-0"><table className="w-full min-w-[580px] text-left text-sm"><thead className="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-slate-500 dark:border-slate-800 dark:bg-slate-800/50"><tr><th className="px-6 py-4">Payment date</th><th className="px-6 py-4">Amount</th><th className="px-6 py-4">Status</th><th className="px-6 py-4"></th></tr></thead><tbody>{payments.map(payment => { const paid = payment.status === "PAID"; const attention = payment.status === "PENDING" || payment.status === "OVERDUE"; return <tr key={payment.id} className="border-b border-slate-100 last:border-0 dark:border-slate-800"><td className="px-6 py-5 font-semibold">{payment.paymentDate.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" })}</td><td className="px-6 py-5 font-medium">{currency.format(payment.amount.toNumber())}</td><td className="px-6 py-5"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${paid ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300" : attention ? "bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300" : "bg-rose-50 text-rose-700 dark:bg-rose-950 dark:text-rose-300"}`}>{displayStatus(payment.status)}</span></td><td className="px-6 py-5 text-right">{paid && <button className="text-sm font-semibold text-violet-600">Receipt</button>}</td></tr>})}</tbody></table>{payments.length === 0 && <p className="p-6 text-sm text-slate-500">No payment records found.</p>}</div></>;
}
